# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-25 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170525_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='androidsignal',
            old_name='name',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='arduinosignal',
            old_name='name',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='arduinosignal',
            name='weight',
        ),
        migrations.AddField(
            model_name='androidsignal',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='androidsignal',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='androidsignal',
            name='z',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='arduinosignal',
            name='frequency',
            field=models.FloatField(default=0),
        ),
    ]
